@TaskFlow.API_HostAddress = http://localhost:5221

### Me Endpoint Testi
GET {{TaskFlow.API_HostAddress}}/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwib3JnYW5pemF0aW9uSWQiOiIxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc2Nzg1NzU5NCwiaXNzIjoiVGFza0Zsb3ciLCJhdWQiOiJUYXNrRmxvd1VzZXJzIn0.DDM5StzRACdKp871e6CQ1VbDtVbDBUtW_nFa9u4L2kk
Accept: application/json